### ISSUE TITLE
question about data generation with statistical-dependence

### ISSUE THREAD

**Issue by TangTangFei** [ysharma1126/ssl_identifiability#1]
Hi, thanks for sharing the code here, very nice paper.

I have a question about your data generation process, it seems that the covariance matrix is sampled for every batch when `statistical-dependence` is specified to be True (https://github.com/ysharma1126/ssl_identifiability/blob/c2968e5a41d6b95f60e7d2c517bb06ca06662e23/spaces.py#L68). 

Doesn't this mean that the statistical dependence is only within one batch, and on average for the whole dataset with many batches, the covariance matrix becomes identity, i.e. no statistical dependence?

Or is there any other reasoning that i'm missing?

**Comment by ysharma1126** [comment]
You are correct, thanks for noticing this oversight and calling it to our attention. Expect an update soon.

**Comment by ysharma1126** [comment]
We have updated the git repo, and will update the arxiv shortly with the corresponding results and appropriate acknowledgement. Thanks again for noticing this issue and reporting it, we really appreciate it!
