### ISSUE TITLE
Difference between raw latents and latents ?

### ISSUE THREAD

**Issue by kfarivar** [ysharma1126/ssl_identifiability#2]
Hello,

1. I was wondering what the difference between the `raw_latents_*.npy` and `latents_*.py ` is ? both seem to be 10 variables per image. raw latents seem to be the actual value of object position, hue, rotation and spotlight position and hue and background hue. 

2. Also, what is the exact order of these attributes ?

thank you.

**Comment by ysharma1126** [comment]
In `raw_latents_*.npy`, all latent variables are in the range [-1, 1]. 
In `latents_*.py `, the latents are rescaled for rendering, which was done using an updated version of the following [script](https://github.com/brendel-group/cl-ica/blob/master/tools/3dident/generate_clevr_dataset_images.py).

For the order of the attributes, see the following [multiline comment](https://github.com/brendel-group/cl-ica/blob/master/tools/3dident/generate_clevr_dataset_latents.py#L33).

**Comment by kfarivar** [comment]
Thank you, it is more clear now.
