### ISSUE TITLE
The performance evaluation for the numerical data is not good as the performance during the training process.

### ISSUE THREAD

**Issue by Haiyao-Nero** [ysharma1126/ssl_identifiability#3]
Hi, there is a problem when I run the code for numerical data. the $R^2$ for evaluation is much lower than that during the training process. The reason may be that the decoder $f$ in the evaluation is different from the $f$ in the training. But only the trained $g$ is saved. Is this a mistake or the $f$ s could be different?

**Comment by ysharma1126** [comment]
Hi, you need to specify the seed, or else you're evaluating the trained model on a different data generating process.

**Comment by Haiyao-Nero** [comment]
Thanks, got it.
